[tool.poetry]
name = "discord-reminder-bot"
version = "1.0.0"
description = "Discord bot that allows you to set date, cron and interval reminders."
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/TheLovinator1/discord-reminder-bot"
repository = "https://github.com/TheLovinator1/discord-reminder-bot"
keywords = [
    "bot",
    "discord",
    "discord-reminder-bot",
    "discord-py-slash-command",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/TheLovinator1/discord-reminder-bot/issues"

[tool.poetry.scripts]
bot = "discord_reminder_bot.main:start"

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^0.21.0"
apscheduler = "^3.9.1"
dateparser = "^1.1.2"
sqlalchemy = "^1.4.42"
discord-py-interactions = { git = "https://github.com/interactions-py/library.git", rev = "unstable" }
interactions-wait-for = "^1.0.6"
dinteractions-paginator = { git = "https://github.com/interactions-py/paginator.git", rev = "unstable" }
discord-webhook = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"